DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_data;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE user_data (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  passport_number INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES user (id)
); 
